### PR TITLE
fix(docs): fix issues in api section

### LINKED ISSUE #932: "Copy Code" Functionality Not Working on API Docs
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Other

### Expected Behavior / Content

When clicking the "Copy Code" button, the code should be copied to the clipboard so I can easily paste it into my project.

### Observed Behavior / Content

Clicking the button doesn't copy the code

### To Reproduce

_No response_

### Environment Details (Optional)

_No response_

### Failure Logs (Optional)

_No response_

### Additional Information (Optional)

_No response_

### LINKED ISSUE #934: AI Enginer Chat API Examples not working
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Technical Bug (unexpected behavior)

### Expected Behavior / Content

Examples should work on documentation website and using curl or postman.

### Observed Behavior / Content

The examples on the website currently do not execute. 

Another issue is if we try to use curl commands or Postman, on our machine:
The below command works:
curl 'https://agentverse.ai/v1beta1/engine/chat/sessions' \
  --header 'Authorization: Bearer <Copy_your_fauna_token>' \
  --header 'Content-Type: application/json' \
  --data-raw '{"requestedModel":"talkative-01","email":"<Copy_your_email>", "functionGroup":"523a7194-214f-48fd-b5be-b0e953cc35a3"}'
  
 However, the example data is:
 curl 'https://agentverse.ai/v1beta1/engine/chat/sessions' \
  --header 'Authorization: Bearer <Copy_your_fauna_token>' \
  --header 'Content-Type: application/json' \
  --data-raw '{"requestedModel":"talkative-01","email":"<Copy_your_email>", "functionGroup":"ef6937d9-c086-4785-8bb1-748680821714"}
  
 The above curl with the example does not work.
 
 The reason is the functionGroup. 
 
 Kindly update the functionGroup to a working value.

To avoid this issue in the future, maybe asking the user to do a GET query for list of the available functionGroups can be mentioned in the documentation, I can see something for that here: https://github.com/fetchai/ai-engine-sdk-python/blob/e2b6c5435c051e21be67d0f572e55df14906ff50/ai_engine_sdk/client.py#L283

Quick fix would be to just update the functionGroup value in the examples.

Kindly do the needful.
 
 

### To Reproduce

_No response_

### Environment Details (Optional)

_No response_

### Failure Logs (Optional)

_No response_

### Additional Information (Optional)

_No response_

### LINKED ISSUE #935: Outdated documentation for AI Engine Chat API
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Incorrect or missing Content

### Expected Behavior / Content

Documentation should capture the latest API Key based approach for getting the Bearer token.

### Observed Behavior / Content

The docs currently ask the user to copy the fauna token from the Agentverse website using Application Tab in the developer mode on the browser. 

However a new method for getting an "API Key" has been added to Agentverse. 

This should be updated in the documentation.

### To Reproduce

_No response_

### Environment Details (Optional)

_No response_

### Failure Logs (Optional)

_No response_

### Additional Information (Optional)

_No response_

### LINKED ISSUE #937: AI Engine Functions API Issue
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Incorrect or missing Content

### Expected Behavior / Content

Curl command copied from docs should work.

### Observed Behavior / Content

Link: https://fetch.ai/docs/apis/ai-engine/functions

Issue: 
The curl command that is included in the docs is:
curl \
-X POST \
-H Authorization: bearer <your token here> \
https://agentverse.ai/v1beta1/functions/ \
 -d '{"agent":"agent1qdnt5j8wr7cyzupu759w79scp3uaz50m33lfqazsf2tpfz84qfazjgnvfvy","name":"Stock price function","description":"Retrieves the stock price of a share.","protocolDigest":"proto:05c3504f6d6486792e8410c9d1c6d626991fc8e0007bae960acb2ab1dd83072a","modelDigest":"model:4ec922f7f18419cf7c6742f96eb4543a7ed5c131af077ca2b267607f65e62eb2","modelName":"StockPrice/StocksProtocol","arguments":[{"name":"symbol","required":true,"type":"string","description":"The symbol of the share, for example: AAPL, GOOG, MSFT, etc."}],"type":"PRIMARY","metadata_properties":{"geo_location":{"location":{"lat":52.205338,"lon":0.121817},"radius":10}}}'
 
 The issue is that this does not contain the -H 'Content-Type: application/json' which is required by the API to parse the object. Should be updated to:
 curl \
-X POST \
-H 'Authorization: Bearer <your token here> ' \
https://agentverse.ai/v1beta1/functions/ \
 -d '{"agent":"agent1qdnt5j8wr7cyzupu759w79scp3uaz50m33lfqazsf2tpfz84qfazjgnvfvy","name":"Stock price function","description":"Retrieves the stock price of a share.","protocolDigest":"proto:05c3504f6d6486792e8410c9d1c6d626991fc8e0007bae960acb2ab1dd83072a","modelDigest":"model:4ec922f7f18419cf7c6742f96eb4543a7ed5c131af077ca2b267607f65e62eb2","modelName":"StockPrice/StocksProtocol","arguments":[{"name":"symbol","required":true,"type":"string","description":"The symbol of the share, for example: AAPL, GOOG, MSFT, etc."}],"type":"PRIMARY","metadata_properties":{"geo_location":{"location":{"lat":52.205338,"lon":0.121817},"radius":10}}}' \
-H 'Content-Type: application/json'

Also note, the quote marks around the Authorization: Bearer <your token here>.

Another issue that I can see which is already pending is that the copy button currently does not work. Mentioned in https://github.com/fetchai/docs/issues/932

### To Reproduce

_No response_

### Environment Details (Optional)

_No response_

### Failure Logs (Optional)

_No response_

### Additional Information (Optional)

_No response_

### PR DESCRIPTION
**Pull request by gautamgambhir97**
## Linked Issues
closes #937 
closes #935 
closes #934 
closes #932 

## Types of changes

_What type of change does this pull request make (put an `x` in the boxes that apply)?_

- [ ] Content update.
- [x] Bug fix (non-breaking change that fixes an issue).
- [ ] New feature added (non-breaking change that adds functionality).
- [x] Breaking change (fix or feature that would cause existing functionality to stop working as expected).
- [ ] Something else (e.g., tests, scripts, example, deployment, infrastructure).

## Checklist

_Put an `x` in the boxes that apply:_

- [x] I have read the [CONTRIBUTING](https://github.com/fetchai/docs/blob/main/CONTRIBUTING.md) guide
- [x] Checks and tests pass locally

## Further comments

_[if this is a relatively large or complex change, kick off a discussion by explaining why you chose the solution you did, what alternatives you considered, etc...]_

### CODE REVIEW

File: components/api-endpoint.tsx [hunk 1]
```diff
@@ -157,23 +157,32 @@ const CurlCodeTab: React.FC<{
 curl \\
 -X ${method} \\
 ${
-  isBearerTokenRequired ? `-H Authorization: bearer <your token here> \\\n` : ""
+  isBearerTokenRequired
```
Comment (devjsc) [inline components/api-endpoint.tsx:160]: this fmt doesn't look right?

**Review by devjsc — CHANGES_REQUESTED** [review]
